### ISSUE TITLE
No Module ModelTools

### ISSUE THREAD

**Issue by thast** [grosenkj/telluricpy#3]
![screenshot 2016-06-16 16 13 57](https://cloud.githubusercontent.com/assets/13682747/16136196/798ff062-33dd-11e6-8d62-bb96202043ad.png)

**Comment by thast** [comment]
PS: I'm on "dev" branch.

**Comment by thast** [comment]
@grosenkj : Thanks for the modification. There is still the same issue wiithin the VTKtools/extraction.py file.

**Comment by grosenkj** [comment]
@thast : I fixed it and push. Thanks for the taking the time to help with this and using the code.

Let me know if you have any other issues.

**Comment by thast** [comment]
@grosenkj : Here is an error report I had by deactivating myself ModelTools and I still got it with the latest push: It has to do with polydata and VTKtools.
![screenshot 2016-06-17 10 59 27](https://cloud.githubusercontent.com/assets/13682747/16160057/e9ce0754-347a-11e6-8df1-92a36e5d365c.png)

**Comment by grosenkj** [comment]
That was my fault. I as trying to import vtkTools inside itself. I can't do that. Now works for me.

**Comment by thast** [comment]
Thanks @grosenkj !  It seems to run properly now. I'm playing with it all day and will let you know my progress/issues!
